export const routes = {
    Discover: "/discover",
    Index: "/",
    Chat: "/chat",
    Match: "/match",
    Profile: "/profile",
    Form: "/form",
    ProfileEdit: "/profile/edit",
    Settings: "/settings",
    Notifications: "/notifications",
    Search: "/search",
    CategoryManagement: "/admin/category",
    Login: "/login",
    Networking: "/networking",
    Vacancies: "/vacancies",
    Startups: "/startups",
    News: "/news",
}