spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_MEDIA_DB}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

    hikari:
      auto-commit: false
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

#    template:
#      exchange: internal.exchange
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: false

s3:
  url: ${S3_URL}
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucketName: ${S3_BUCKET}

server:
  port: 8082

ffmpeg_path: ${FFMPEG_PATH}