server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gateway:
#      default-filters:
#        - name: AddRequestHeader
#          args:
#            name: X-Real-IP
#            value: your-client-id-value
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: ${CLIENT_URL}
#            allowedMethods:
#              - GET,POST,PUT,OPTIONS,OPTION
      routes:
        - id: category
          uri: ${CATEGORIES_URL}
          predicates:
            - Path=/api/v2/categories/**
            - Method=GET,POST,DELETE
          filters:
            - JwtUserIdFilter
        - id: post
          uri: ${POSTS_URL}
          predicates:
            - Path=/api/v2/post/**
          filters:
            - JwtUserIdFilter
        - id: finder
          uri: ${FINDER_URL}
          predicates:
            - Path=/api/v2/profiles/**
#          filters:
#            - JwtUserIdFilter
#        - id: auth
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/auth/**
        - id: media
          uri: ${MEDIA_URL}
          predicates:
            - Path=/api/v2/media/**
            - Method=GET

app:
  cors: ${CLIENT_URL}
  auth_server: ${AUTH_SERVER_URL}
#  cors: http://localhost:5173

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG