server:
  port: 8090

spring:
  cloud:
    gateway:
#      default-filters:
#        - name: AddRequestHeader
#          args:
#            name: X-Real-IP
#            value: your-client-id-value
      routes:
        - id: category
          uri: ${CATEGORIES_URL}
          predicates:
            - Path=/api/v2/categories/**
            - Method=GET,POST
        - id: post
          uri: ${POSTS_URL}
          predicates:
            - Path=/api/v2/post/**
        - id: finder
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/profiles/**
#          filters:
#            - JwtUserIdFilter
#        - id: auth
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/auth/**
        - id: media
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/media/**
            - Method=GET

app:
  cors: ${CLIENT_URL}
#  cors: http://localhost:5173