spring:
#  config:
#    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: finder-app
  datasource:
    username: ${PG_USERNAME}
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_DB}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queue: ${RABBIT_QUEUE}

    listener:
      simple:
        acknowledge-mode: auto
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

server:
  port: 8071

api:
  media_server: ${MEDIA_URL}
  category_server: ${CATEGORIES_URL}